diff_cont:
  ros__parameters:

    publish_rate: 1000.0

    base_frame_id: base_footprint

    left_wheel_names: ['base_to_left_wheel']
    right_wheel_names: ['base_to_right_wheel']
    wheel_separation: 0.35
    wheel_radius: 0.036

    use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    #publish_limited_velocity: 0.5
    # velocity_rolling_window_size: x
    
    linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    #angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
    